########################################################################################################################
# common
########################################################################################################################

spring:
  profiles:
    active: development

server:
  port: 8888
  tomcat:
    accesslog:
      enabled: true
---
########################################################################################################################
# development
########################################################################################################################
spring:
  config:
    activate:
      on-profile: development

  jackson:
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: true

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    generate-unique-name: true
    url: jdbc:mariadb://localhost:33307/rest
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password:

    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
      leak-detection-threshold: 60000

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

logging:
  level:
    root: INFO
    org:
      springframework:
        web: DEBUG
        web.servlet.mvc.method.annotation: TRACE

server:
  tomcat:
    accesslog:
      enabled: true

---